initia-labs/initia

README.md

Fix broken links related to Initia App,Initia Usernames

Fix: Initia App,Initia Usernames broken links in README.md

---

app/app.go
go.mod
go.sum

This update of the `x/forwarding` module includes the `AllowedDenoms` feature requested by your team.

chore: update forwarding module

---

cmd/initiad/indexer.go

indexer needs auth key only for now

listen auth key only

---

x/move/keeper/handler.go
x/move/types/expected_keeper.go

fix: remove account before overwriting to avoid primary constraints

---

x/distribution/keeper/common_test.go
x/distribution/keeper/custom_msg_server_test.go
x/distribution/keeper/grpc_query_test.go
x/distribution/keeper/keeper.go
x/distribution/keeper/msg_server_test.go
x/mstaking/keeper/msg_server_test.go

distribution
- msg server
- custom msg server
- grpc query server
mstaking
- msg server

test: test code for distribution & mstaking msg server

---

x/distribution/keeper/delegation.go
x/move/types/denom.go
x/move/types/denom_test.go

* add missing error handling
* add case check in MetadataAddressFromDenom

fix: add missing error handling

---

x/ibc-hooks/move-hooks/ack.go
x/ibc-hooks/move-hooks/hooks.go
x/ibc-hooks/move-hooks/timeout.go

* allow cosmos address in ack callback
* do not return error in callback logics (ack, timeout)

fix: do not return error in ack and timeout

---

go.mod
go.sum

https://github.com/cometbft/cometbft/blob/v0.38.9/CHANGELOG.md#v0389

feat: use apply latest comet update

---

Dockerfile
go.mod
go.sum
images/private/Dockerfile

bump: movevm to v0.3.4

---

app/ante/accnum/account_number.go
app/ante/ante.go
app/ante/sigverify/sigverify.go
app/ante/sigverify/verify.go

separate ante implementations from ante handler to avoid movevm dependency from minitias

feat: separate ante implementation

---

.github/workflows/lint.yml
Makefile
app/ante/sigverify/verify.go
app/app.go
tx/eip191.go
x/move/abci.go
x/move/client/cli/query.go
x/move/keeper/staking.go
x/move/types/connector.go

seems all previous golangci-lint have been skipped
* new action follows a similar procedure to cosmos-sdk
* non-JSON queries/executions are marked as nolint

fix lint action

---

x/reward/types/genesis.go

fix: use UTC for genesis

---

app/slinky.go

Closes: #XXXX
---
I have...
I have...

fix: wrap oracle client to feed timestamp

---

.github/workflows/dependency-review.yml

github action to review dependencies
---
I have...
I have...

chore: review dependencies

---

x/ibc-hooks/move-hooks/receive.go
x/ibc-hooks/move-hooks/receive_test.go
x/ibc-hooks/move-hooks/util.go
x/ibc/nft-transfer/types/packet.go

Closes: #XXXX
---
I have...
I have...

fix: encode intermediate sender changed packet with counterparty port consideration

---

Dockerfile
go.mod
go.sum

Closes: #XXXX
---
I have...
I have...

fix: bump movevm to fix json and events

---

Dockerfile
go.mod
go.sum

Closes: #XXXX
---
I have...
I have...

bump movevm to v0.4.4

---

.golangci.yml

Closes: #XXXX
---
I have...
I have...

disable typecheck

---

Dockerfile
go.mod
go.sum

Add json native functions
---
I have...
I have...

bump: movevm to v0.4.11 

---

x/gov/client/cli/query.go

Closes: #XXXX
---
I have...
I have...

feat: gov cli to use custom query for tallying

---

Dockerfile
go.mod
go.sum

Closes: #XXXX
---
I have...
I have...

bump movevm to v0.4.12 to update stadlibs

---

go.mod
go.sum

Closes: #XXXX
---
I have...
I have...

bump OPinit to fix FinalizeWithdrawal

---

x/gov/keeper/custom_grpc_query_test.go
x/gov/keeper/tally_test.go
x/ibc/perm/client/cli/cli.go
x/ibc/perm/client/cli/tx.go
x/ibc/perm/module.go

Closes: #XXXX
---
I have...
I have...

feat: add missing ibc perm cmd

---

app/upgrade.go
go.mod
go.sum
x/move/types/params.go

Align OPinit version with minitias
Closes: #XXXX
---
I have...
I have...

bump: opinit

---

app/const.go

Closes: #XXXX
---
I have...
I have...

feat: decrease fee deduct gas

---

.github/workflows/build-linux-amd64.yml

Closes: #XXXX
just did `make build-linux`
---
I have...
I have...

chore: release stataically-built binary with _static postfix

---

go.mod
go.sum

https://github.com/initia-labs/OPinit/releases/tag/v0.5.6
This may solve json codec problems.
---
I have...
I have...

bump opinit to v0.5.6

---

app/lanes/default.go
app/lanes/free.go
app/lanes/free_test.go
app/lanes/mempool.go
app/lanes/mempool_test.go
app/lanes/system.go

Closes: #296 
---
I have...
I have...

feat: return mempool error, if a tx exceeds lane limits

---

.golangci.yml

Closes: #XXXX
---
I have...
I have...

fix: lintci

---

.github/workflows/build-linux-amd64.yml
.github/workflows/build-linux-arm64.yml

cosmovisor cannot handle subdirectory in previous linux releases.
so fixed the workflows to not make subdirectory.
fyi, darwin releases don't have subdirectory anyway
---
I have...
I have...

chore: remove subdirectory in linux releases

---

.github/workflows/lint.yml
x/gov/abci.go
x/gov/abci_test.go
x/gov/common_test.go
x/gov/types/params.go
x/gov/types/params_test.go

emergency proposals are not tallied in normal voting end time, but it should be tallied.
---
I have...
I have...

fix: emergency poll should be finished if voting period is over

---

cmd/flags/comet.go
cmd/initiad/root.go

Closes: #XXXX
---
I have...
I have...

feat: add statesync flags

---

go.mod
go.sum

Previously, we did not prune the `tx.height`, `tx.hash`, or `block.height`, even though we set `[txindex].retain-height` to a non-zero value. This resulted in the continuous accumulation of transaction indexing data. To prevent the need for state synchronization every few days, we've decided to remove the practice of indefinitely increasing transaction indexing data.
---
I have...
I have...

bump: CometBFT to update `txindex` pruning strategy

---

go.mod
go.sum

Closes: #XXXX
---
I have...
I have...

chore: bump ibc-go 

---

client/docs/swagger-ui/swagger.yaml

Closes: #XXXX
---
I have...
I have...

chores: update swagger docs

---

go.mod

resolve https://github.com/golang/go/issues/69978
---
I have...
I have...

chore: bump go version

---

x/move/keeper/dex.go

Closes: #XXXX
---
I have...
I have...

fix: gas prices endpoint to return base denom price too

---

x/move/keeper/dex.go
x/move/keeper/dex_test.go

Closes: #XXXX
---
I have...
I have...

fix: dex gas price

---

crypto/keyring/ledger.go
crypto/keyring/ledger_notavail.go

Closes: #XXXX
---
I have...
I have...

fix: add build options to prevent docker build fail

---

go.mod
go.sum

Closes: #XXXX
---
I have...
I have...

chore: bump ibc-go version

---

crypto/keyring/options.go
crypto/ledger/accounts/account.go
crypto/ledger/accounts/errors.go
crypto/ledger/accounts/hd.go
crypto/ledger/accounts/hd_test.go
crypto/ledger/accounts/url.go
crypto/ledger/accounts/url_test.go
crypto/ledger/ledger.go
crypto/ledger/ledger_mock.go
crypto/ledger/ledger_notavail.go
crypto/ledger/usbwallet/hub.go
crypto/ledger/usbwallet/ledger.go
crypto/ledger/usbwallet/wallet.go
go.mod
go.sum

remove replace but add packages on initia
---
I have...
I have...

chore: remove go-ethereum replace

---

app/genesis.go
app/genesis_markets/markets.go
go.mod
go.sum

Closes: #XXXX
---
I have...
I have...

bump: cosmos-sdk to latest

---

README.md
app/ante/sigverify/sigverify.go
x/distribution/keeper/custom_msg_server.go
x/gov/keeper/custom_msg_server.go
x/gov/types/params.go
x/ibc-hooks/move-hooks/README.md

- fix typos
---
I have...
I have...

chores: fix typos

---

app/genesis_markets/markets.go
crypto/keyring/options.go
crypto/ledger/ledger.go
crypto/ledger/ledger_mock.go
crypto/ledger/ledger_notavail.go
go.mod

Closes: #XXXX
---
I have...
I have...

feat: multi ledger support

---

.github/workflows/docker.yml
Dockerfile
Makefile

Closes: #XXXX
---
I have...
I have...

fix(docker): set initiad version in docker image

---

app/ante/sigverify/verify.go
cmd/initiad/root.go
crypto/ethsecp256k1/ethsecp256k1.go
crypto/keyring/keyring.go
crypto/ledger/ledger.go
go.mod
go.sum
tx/eip191.go

Closes: #XXXX
---
I have...
I have...

fix: sigverify to attach eip191 prefix, only it is legacy amino json mode

---

client/docs/config.json
client/docs/swagger-ui/swagger.yaml

Closes: #XXXX
---
I have...
I have...

fix: add dynamic fee to swagger config 

---

crypto/ledger/usbwallet/hub.go

When I have test the recently brought ledger devices, those devises are returning following product ids.
```go
// The USB product IDs will be defined as MMII, encoding a model (MM) and an interface bitfield (II)
0x1000, /* Ledger Nano S */
0x4000, /* Ledger Nano X */
0x5000, /* Ledger Nano S Plus */
0x6000, /* Ledger Nano FTS */
```
---
I have...
I have...

fix: add supported product id

---

x/ibc-hooks/move-hooks/receive.go
x/ibc-hooks/move-hooks/receive_test.go
x/ibc-hooks/move-hooks/util.go
x/ibc-hooks/move-hooks/util_test.go

add hashed address check to hook receiver validation

---

app/upgrade.go
go.mod
go.sum

This PR prepares for the v1.1.x chain upgrades, introducing minor interface changes.
You can see full changes [here](https://github.com/initia-labs/initia/compare/v1.0.0...release/v1.1.x).
---
I have...
I have...

upgrade(v1.1.x): prepare v1.1.x release

---

x/dynamic-fee/ante/fee.go
x/dynamic-fee/ante/fee_test.go

Closes: #407 
---
I have...
I have...

fix: use gas price at mempool priority instead of fee amount

---

scripts/protoc-swagger-gen.sh

to support case-sensitive filesystems
---
I have...
I have...

chore(swagger): fix OPinit path in script to generate swagger

---

README.md

Closes: #XXXX
---
I have...
I have...

docs: add build&test badge

---

x/move/keeper/handler.go

Closes: #XXXX
---
I have...
I have...

fix: emit move data event for backward compatibility

---

Dockerfile
go.mod

update go.mod to use latest movevm version 
---
I have...
I have...

fix: movevm version to latest

---

cmd/initiad/root.go
crypto/keyring/keyring.go
crypto/keyring/options.go

Closes: #395 
---
I have...
I have...

fix: prevent cosmos-sdk to override keyring
