initia-labs/initia

go.mod, go.sum
Bumps the block sdk version to the most recent 2.X release.  
This contains a fix for a bug which causes RPC nodes to accumulate stuck transactions in their mempools over time.
=> Bump blocksdk version

app/app.go, app/lanes/proposals.go
- We change the default lane prepare logic for default / free lanes to continue it's search for txs even if it finds a transaction that exceeds the gas / bytes limit for the block
=> fix: continue searching for txs after finding one that exceeds the max bytes / gas limit

x/mstaking/client/cli/tx.go
Use the correct argument for destination validator address in x/mstaking relegate tx cmd.
=> fix: arguments for redelegate tx cmd

app/lanes/proposals.go
**related issue:** https://github.com/initia-labs/initia/issues/180
**downgrade log-level:**
I downgraded the log level because the log of the change made in this commit, were too numerous and not critical.
Tx selection algorithm during preparing lane is greedy algorithm meaning it iterates every transaction. If mempool has bunch of transactions, and block is almost reached its limit then log can be generated for rest of txs in a mempool.
**fix comment:**
Current tx selection algorithm is greedy algorithm, it does not break during iteration.
=> chore: downgrade log-level for noisy but not critical logs and fix comment

app/app_test.go, go.mod, go.sum, x/move/abci_test.go, x/move/ante/ante_test.go, x/move/ante/fee_test.go, x/move/ante/gas_prices_test.go, x/move/common_test.go, x/reward/abci_test.go
related: https://github.com/cosmos/cosmos-sdk/pull/20686
=> fix: use versioned cms to take snapshot at simulation and check tx

Dockerfile, app/app.go, benchmark/app_test.go, go.mod, go.sum, images/private/Dockerfile, x/move/keeper/api.go, x/move/keeper/api_test.go, x/move/keeper/bank.go, x/move/keeper/genesis.go, x/move/module.go, x/move/types/connector.go
need to bump movevm 
https://github.com/initia-labs/movevm/pull/73
=> feat: blocked addrs

Dockerfile
fix for issue - [Docker buildkit build for linux/amd64 failed on apple silicon machine. #169](https://github.com/initia-labs/initia/issues/169)
This docker file allows you to clearly build a multi-platform image.
In this Dockerfile version, it added specific env for GOARCH.
=> fix: Update Dockerfile for building multiplatform clearly.

x/distribution/keeper/delegation.go, x/distribution/keeper/validator.go
The bug comes from the setting the outstanding rewards with wrong key.
```diff
- err = k.ValidatorOutstandingRewards.Set(ctx, delAddr, customtypes.ValidatorOutstandingRewards{Rewards: outstanding.Sub(rewards)})
+ err = k.ValidatorOutstandingRewards.Set(ctx, valAddr, customtypes.ValidatorOutstandingRewards{Rewards: outstanding.Sub(rewards)})
```
=> fix: withdrawal bugfix

app/ante/account_number.go, app/ante/ante.go, go.mod, go.sum
This is temporal solution to avoid account number collision error, which is occurred due to async Simulate, Finalize, CheckTx.
- https://github.com/cosmos/cosmos-sdk/issues/20685
This update is only works at (re)checkTx and Simulate mode and update account number to cache store by adding 1_000_000 and 2_000_000 according to exec mode. This will make each mode run the ante and msgs over this updated account number.
=> fix: use AccountNumberDecorator to avoid account number collision

app/keepers/keepers.go
Closes: #XXXX
---
I have...
I have...
=> feat: add stargate query support for staking related queries

x/move/ante/gas_prices.go, x/move/keeper/staking.go, x/move/types/connector.go
Closes: #XXXX
---
I have...
I have...
=> feat: audit

x/distribution/keeper/allocation.go, x/move/ante/fee.go, x/move/ante/fee_test.go, x/move/keeper/dex.go, x/move/keeper/dex_test.go, x/move/types/connector.go, x/move/types/connector_test.go, x/move/types/exported.go
Closes: #XXXX
---
I have...
I have...
=> fix: audit

Dockerfile, cmd/move/move.go, go.mod, go.sum
Closes: #XXXX
---
I have...
I have...
=> feat: introduce named-addresses

x/move/keeper/genesis.go, x/move/keeper/handler.go, x/move/keeper/keeper.go, x/move/keeper/vmpool.go
Closes: #XXXX
We cannot share vm across threads until loader v2 installed, so create this vm pool. [details](https://github.com/aptos-labs/aptos-core/blob/5ad601cc4bb5adeb086721a4d57ca3014119c77f/third_party/move/move-vm/runtime/src/loader/mod.rs#L2090-2094)
```rust
// TODO: If the VM is not shared across threads, this error means that there is a
//       recursive type. But in case it is shared, the current implementation is not
//       correct because some other thread can cache depth formula before we reach
//       this line, and result in an invariant violation. We need to ensure correct
//       behavior, e.g., make the cache available per thread.
```
---
please add links to any relevant follow …
=> feat: introduce vmpool to make each vm run on single thread

x/move/keeper/genesis.go, x/move/keeper/handler.go
Closes: #XXXX
---
I have...
I have...
=> fix: release vm right after execution finished

app/upgrade.go, go.mod, go.sum, x/ibc/perm/keeper/keeper.go
Closes: #XXXX
---
I have...
I have...
=> fix: has relayer permission

x/move/keeper/keeper.go
Use only one VM for now because we need to clear the cache on every module upgrade.
But if we have multiple VMs, only the VM that executed the module upgrade will have the cache cleared.
---
I have...
I have...
=> fix: use a single vm

app/keepers/keepers.go
Closes: #XXXX
---
I have...
I have...
=> fix: nil memory access on authz module

x/move/keeper/handler.go, x/move/keeper/handler_test.go
Closes: #XXXX
---
I have...
I have...
=> fix: allow to be failed with invalid message without error

x/move/keeper/handler.go
When we pass gas balance to movevm, then movevm will multiply it by scaleFactor (100) to scale it up to movevm unit. To avoid overflow in this process, we need to divide gasForRuntime when we use infinity gas meter. 
Closes: #XXXX
---
I have...
I have...
=> fix: consider movevm gas scale factor

x/ibc-hooks/move-hooks/receive.go
Closes: #XXXX
---
I have...
I have...
=> fix: use cache context at ibc hook

x/bank/keeper/common_test.go, x/distribution/keeper/common_test.go, x/gov/keeper/common_test.go, x/ibc-hooks/keeper/common_test.go, x/ibc-hooks/move-hooks/common_test.go, x/move/keeper/common_test.go, x/move/keeper/genesis.go, x/move/keeper/staking_test.go, x/mstaking/keeper/common_test.go, x/reward/keeper/common_test.go, x/slashing/keeper/common_test.go
Closes: #XXXX
---
I have...
I have...
=> fix: initialize staking at genesis

x/ibc-hooks/move-hooks/receive.go
We already branching the context before executing `execMsg`, so don't need to do another branching for execute.
---
I have...
I have...
=> fix: remove unnecessary context branching

Dockerfile, go.mod, go.sum
Bump movevm to [v0.6.1](https://github.com/initia-labs/movevm/releases/tag/v0.6.1) to introduce ibctesting feature.
---
I have...
I have...
=> feat: introduce ibctesting feature

app/upgrade.go, go.mod, go.sum
Closes: #XXXX
---
I have...
I have...
=> release: prepare v0.6.2 release

cmd/move/move.go
Change default move version to v2 in move cmd.
---
I have...
I have...
=> feat: move v2 as default in the move cmd

app/upgrade.go, x/ibc-hooks/move-hooks/message.go, x/ibc-hooks/move-hooks/message_test.go
Closes: #XXXX
The IBC callback can use a standard JSON decoder, which allows only numbers as valid async callback IDs. However, our MoveVM JSON encoder encodes uint64 values as strings. To maintain consistency with this implementation, our AsyncCallback uses a custom UnmarshalJSON method, which accommodates both string and numeric callback IDs.
---
I have...
I have...
=> fix: allow string callback id

x/ibc/nft-transfer/keeper/integration_test.go, x/ibc/nft-transfer/keeper/relay.go, x/ibc/nft-transfer/types/expected_keeper.go
This PR contains consensus breaking changes, so should be shipped with upgrade.
---
I have...
I have...
=> feat!: create account if NFT recipient account does not exist

x/ibc/nft-transfer/types/packet.go, x/ibc/nft-transfer/types/packet_test.go
- Add duplicate token id check in NonFungibleTokenPacketData.ValidateBasic()
- Prevent potential issues with duplicate token ids in NFT transfers
- Improve IBC NFT transfer security and reliability
---
I have...
I have...
=> fix(ibc-nft): add duplicate token id validation in packet data

x/ibc-hooks/move-hooks/message.go, x/ibc-hooks/move-hooks/message_test.go
Closes: #317
Improves AsyncCallback JSON unmarshaling with:
- Better validation for ModuleAddress format and required fields
- More specific error messages
- Memory optimization using single intermediate struct
- Comprehensive test coverage for error cases
Fetch this PR branch and from the root directory run:
```bash
go test ./x/ibc-hooks/move-hooks/message_test.go -v
```
---
=> feat(ibc-hooks): improved UnmarshalJSON validation & error handling

app/encoding.go
Refactored to extract the creation of `InitiaApp` instances into a new function `newTempApp()` to reduce duplicated code.
I have...
I have...
=> refactor: refactor app/encoding.go

.github/workflows/build-darwin-amd64.yml
This PR improves the build workflow for Darwin AMD64 by:
1. Fixing the typo in step name (ADM64 -> AMD64)
2. Restructuring the build commands for better readability and maintenance
3. Adding descriptive comments for each build step
4. Improving file handling with proper directory creation and cleanup
No functional changes are introduced, only code organization and naming improvements.
Closes: N/A
I have...
I have...
=> fix: Improve Darwin AMD64 build workflow structure and fix naming

cmd/move/deploy.go, cmd/move/move.go
Add object deployment cmd to help the users to derive object address.
---
I have...
I have...
=> feat: implement object deploy cmd for auto address derivation

x/gov/abci.go, x/gov/abci_test.go
To properly show the voting end time, we need to update voting end time to next emergency tally time at tally handler.
---
I have...
I have...
=> fix: update `voting_end_time` to `next_emergency_tally_time` at tally

app/app.go, app/encoding.go
Currently, upgrade handlers are being registered during the initial encoding configuration setup, which can lead to unintended side effects. Specifically, the Cosmos SDK's upgrade module attempts to create the ${HOME}/.initia/data directory to check for upgrade information, even though this is not required during early-stage setup.
This PR is to register upgrade handlers only when loading the latest version of the app. This optimization prevents unnecessary file system access and handler registration during app initialization, improving startup performance and avoiding redundant operations.
---
I have...
_All items are required. Please add a note if …
=> fix: skip upgrade handler registration if loadLatest is false

x/mstaking/keeper/grpc_query.go, x/mstaking/keeper/grpc_query_test.go
Fix validators query to prevent returning `unbonding` validators which are in `whitelist` but not in `BondedStatus` due to the max num of validators.
---
I have...
I have...
=> fix: validators query to prevent returning unbonding validators

.github/workflows/build-darwin-amd64.yml, .github/workflows/build-darwin-arm64.yml, .github/workflows/build-linux-amd64.yml, .github/workflows/build-linux-arm64.yml, .github/workflows/dependency-review.yml, .github/workflows/docker.yml, .github/workflows/lint.yml, .github/workflows/spellcheck.yml, .github/workflows/test.yml
Bumps checkout to v5 for future-proofing against Node 24 runner updates. Requires runner v2.327.1+. Workflows compile the same.
More info: https://github.com/actions/checkout/releases/tag/v5.0.0
=> CI: migrate workflows to checkout v5
